#!/user/bin/env groovy

library identifier: "08-jenkins-shared-library@main", retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/timmartinberger/08-jenkins-shared-library.git',
    credentialsId: '97fe2288-6e06-4306-99ac-4bd45c00ae7a'])
def gv

pipeline {
    agent any

    tools { // Make maven available for build stage
        maven 'maven-3.9'
    }

    stages {
        stage('Init') {
            steps {
                script {
                    echo "Executing pipeline for $BRANCH_NAME"
                    dir('01-java-maven-app') { // Load from 01-java-maven-app directory
                        gv = load "script.groovy"
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    gv.testApp()
                }
            }
        }
        stage('Build jar') {
            steps {
                script {
                    dir('01-java-maven-app') {
                        buildJar()  // Name of the file containing the buildJar functionality in the shared library
                    }
                }
            }
        }
        stage('Build and push docker image') {
            steps {
                script {
                    dir('01-java-maven-app') {
                        dockerBuild 'aarontimberg/demo-app:jma-2.1' // Name of the file containing the buildImage functionality in the shared library
                        dockerLogin()
                        dockerPush 'aarontimberg/demo-app:jma-2.1'
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                expression {
                    BRANCH_NAME == "main"
                }
            }
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
    }
}
