def gv

pipeline {
    agent any

    tools { // Make maven available for build stage
        maven 'maven-3.9'
    }

    stages {
        stage('init') {
            steps {
                script {
                    echo "Executing pipeline for $BRANCH_NAME" // NOTE: BRANCH_NAME is only available in multibranch pipelines
                    dir('01-java-maven-app') { // Load from 01-java-maven-app directory
                        gv = load "script.groovy"
                    }
                }
            }
        }
        stage('Increment version') {
            steps {
                script {
                    echo "Incrementing app version"
                    dir('01-java-maven-app') {
                        sh 'mvn build-helper:parse-version versions:set \
                            -DnewVersion=\\\${parsedVersion.majorVersion}.\\\${parsedVersion.minorVersion}.\\\${parsedVersion.nextIncrementalVersion} \
                            versions:commit'
                        def matcher = readFile('pom.xml') =~ '<version>(.+)</version>'
                        def version = matcher[0][1] // matcher[0][1] is the actual version inside the pom.xml
                        env.IMAGE_NAME = "jma-$version.$BUILD_NUMBER"
                    }
                }
            }
        }
        stage('test') {
            steps {
                script {
                    dir('01-java-maven-app') {
                        gv.testApp()
                    }
                }
            }
        }
        stage('Build jar') {
            steps {
                script {
                    dir('01-java-maven-app') {
                        gv.buildJar()
                    }
                }
            }
        }
        stage('Build docker image') {
            steps {
                script {
                    dir('01-java-maven-app') {
                        gv.buildImage()
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                expression {
                    BRANCH_NAME == "main"
                }
            }
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
        stage('Commit version update') {
            steps {
                script {
                    withCredentials([usernamePassword(credentialsId: '97fe2288-6e06-4306-99ac-4bd45c00ae7a', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                        sh "git remote set-url origin https://${USER}:${PASS}@github.com/timmartinberger/devops-bootcamp-08-jenkins.git"
                        sh 'git add .'
                        sh 'git commit -m "ci: version bump"'
                        sh 'git push origin HEAD:main'
                    }
                }
            }
        }
    }
}
