def gv

pipeline {
    agent any

    tools { // Make maven available for build stage
        maven 'maven-3.9'
    }

    stages {
        stage('Init') {
            steps {
                script {
                    echo "Executing pipeline for $BRANCH_NAME" // NOTE: BRANCH_NAME is only available in multibranch pipelines
                    dir('01-java-maven-app') { // Load from 01-java-maven-app directory
                        gv = load "script.groovy"
                    }
                }
            }
        }
        stage('Increment version') {
            steps {
                script {
                    dir('01-java-maven-app') {
                        gv.mvnVersioning() // Actual steps sourced out to script.groovy for a clean overview
                    }
                }
            }
        }
        stage('Test') {
            steps {
                script {
                    dir('01-java-maven-app') {
                        gv.testApp()
                    }
                }
            }
        }
        stage('Build jar') {
            steps {
                script {
                    dir('01-java-maven-app') {
                        gv.buildJar()
                    }
                }
            }
        }
        stage('Build and push docker image') {
            steps {
                script {
                    dir('01-java-maven-app') {
                        gv.buildImage()
                    }
                }
            }
        }
        stage('Deploy') {
            when {
                expression {
                    BRANCH_NAME == "main"
                }
            }
            steps {
                script {
                    gv.deployApp()
                }
            }
        }
        stage('Commit version update') {
            steps {
                script {
                    gv.gitCommit()
                }
            }
        }
    }
}
