#!/user/bin/env groovy

library identifier: "08-jenkins-shared-library@main", retriever: modernSCM([
    $class: 'GitSCMSource',
    remote: 'https://github.com/timmartinberger/08-jenkins-shared-library.git',
    credentialsId: '97fe2288-6e06-4306-99ac-4bd45c00ae7a'])



pipeline {
    agent any

    tools {
        nodejs 'nodejs-24.16.0'
    }

    stages {

        stage("Prepare versioning") {
            steps{
                script{
                    dir('02-jenkins-exercises/app'){
                        incrementNpmVersion()
                    }
                }
            }
        }
        stage("Test app") {
            steps{
                script{
                    dir('02-jenkins-exercises/app'){
                        runNpmTest()
                    }
                }
            }
        }
        stage("Build docker image") {
            steps {
                script{
                    dir('02-jenkins-exercises'){
                        def imgName = "nodeapp-${IMAGE_TAG}"
                        dockerBuild imgName
                        dockerLogin()
                        dockerPush imgName
                    }
                }
            }
        }
        stage("Commit new version to git") {
            steps {
                script{
                    dir('02-jenkins-exercises'){
                        withCredentials([usernamePassword(credentialsId: '97fe2288-6e06-4306-99ac-4bd45c00ae7a', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
                            def origin = "https://${USER}:${PASS}@github.com/timmartinberger/devops-bootcamp-08-jenkins.git"
                            def branch = "main"
                            gitCommit origin branch
                        }
                    }
                }
            }
        }
    }
}